# Generated by Django 4.2.4 on 2023-08-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Donor",
        ),
    ]
