# Generated by Django 4.2.4 on 2023-08-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donor", "0002_delete_donor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.TextField(default="", max_length=500)),
                ("gender", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="")),
                ("ready_to_donate", models.BooleanField(default=True)),
                (
                    "blood_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor.bloodgroup",
                    ),
                ),
                (
                    "donor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
