# Generated by Django 4.2.4 on 2023-08-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0002_delete_requestblood"),
        ("donor", "0003_donor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="donor",
        ),
        migrations.DeleteModel(
            name="BloodGroup",
        ),
        migrations.DeleteModel(
            name="Donor",
        ),
    ]
